package cs455.overlay.wireformats;

public interface Protocol {
	static byte OVERLAY_NODE_SENDS_REGISTRATION = 2;
	static byte REGISTRY_REPORTS_REGISTRATION_STATUS = 3;
	static byte OVERLAY_NODE_SENDS_DEREGISTRATION = 4;
	static byte REGISTRY_REPORTS_DEREGISTRATION_STATUS = 5;
	static byte REGISTRY_SENDS_NODE_MANIFEST = 6;
	static byte NODE_REPORTS_OVERLAY_SETUP_STATUS = 7;
	static byte REGISTRY_REQUESTS_TASK_INITIATE = 8;
	static byte OVERLAY_NODE_SENDS_DATA = 9;
	static byte OVERLAY_NODE_REPORTS_TASK_FINISHED = 10;
	static byte REGISTRY_REQUESTS_TRAFFIC_SUMMARY = 11;
	static byte OVERLAY_NODE_REPORTS_TRAFFIC_SUMMARY = 12;

	static String OVERLAY_NODE_SENDS_REGISTRATION_LABEL = "OVERLAY_NODE_SENDS_REGISTRATION";
	static String REGISTRY_REPORTS_REGISTRATION_STATUS_LABEL = "REGISTRY_REPORTS_REGISTRATION_STATUS";
	static String OVERLAY_NODE_SENDS_DEREGISTRATION_LABEL = "OVERLAY_NODE_SENDS_DEREGISTRATION";
	static String REGISTRY_REPORTS_DEREGISTRATION_STATUS_LABEL = "REGISTRY_REPORTS_DEREGISTRATION_STATUS";
	static String REGISTRY_SENDS_NODE_MANIFEST_LABEL = "REGISTRY_SENDS_NODE_MANIFEST";
	static String NODE_REPORTS_OVERLAY_SETUP_STATUS_LABEL = "NODE_REPORTS_OVERLAY_SETUP_STATUS";
	static String REGISTRY_REQUESTS_TASK_INITIATE_LABEL = "REGISTRY_REQUESTS_TASK_INITIATE";
	static String OVERLAY_NODE_SENDS_DATA_LABEL = "OVERLAY_NODE_SENDS_DATA";
	static String OVERLAY_NODE_REPORTS_TASK_FINISHED_LABEL = "OVERLAY_NODE_REPORTS_TASK_FINISHED";
	static String REGISTRY_REQUESTS_TRAFFIC_SUMMARY_LABEL = "REGISTRY_REQUESTS_TRAFFIC_SUMMARY";
	static String OVERLAY_NODE_REPORTS_TRAFFIC_SUMMARY_LABEL = "OVERLAY_NODE_REPORTS_TRAFFIC_SUMMARY";
}